# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import timeMachine_pb2 as timeMachine__pb2


class TimemachineStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Save = channel.unary_unary(
        '/timemachine.Timemachine/Save',
        request_serializer=timeMachine__pb2.SaveRequest.SerializeToString,
        response_deserializer=timeMachine__pb2.ID.FromString,
        )
    self.Get = channel.unary_unary(
        '/timemachine.Timemachine/Get',
        request_serializer=timeMachine__pb2.GetRequest.SerializeToString,
        response_deserializer=timeMachine__pb2.Data.FromString,
        )
    self.GetRange = channel.unary_stream(
        '/timemachine.Timemachine/GetRange',
        request_serializer=timeMachine__pb2.RangeRequest.SerializeToString,
        response_deserializer=timeMachine__pb2.Data.FromString,
        )


class TimemachineServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Save(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TimemachineServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Save': grpc.unary_unary_rpc_method_handler(
          servicer.Save,
          request_deserializer=timeMachine__pb2.SaveRequest.FromString,
          response_serializer=timeMachine__pb2.ID.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=timeMachine__pb2.GetRequest.FromString,
          response_serializer=timeMachine__pb2.Data.SerializeToString,
      ),
      'GetRange': grpc.unary_stream_rpc_method_handler(
          servicer.GetRange,
          request_deserializer=timeMachine__pb2.RangeRequest.FromString,
          response_serializer=timeMachine__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'timemachine.Timemachine', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
